setwd("/Users/raghavanchandran/downloads")
power <- read.table("household_power_consumption.txt", sep = ";", header = TRUE)
power$Date <- as.Date(power$Date,"%d/%m/%Y")
power_flt <- with(power, power[(Date == "2007-02-01"|Date == "2007-02-02" & Global_active_power != '?'),])
power_flt$Global_active_power <- as.numeric(as.character(power_flt$Global_active_power))
P_timestp <- paste(power_flt$Date,power_flt$Time)
power_flt$timestp <- strptime(P_timestp,"%Y-%m-%d %H:%M:%S")
## plot -3 
png(file= "plot3.png")
plot(power_flt$timestp,power_flt$Sub_metering_1, type = "l", xlab = ' ', ylab = "Energy Sub metering", col = "black")
points(power_flt$timestp,power_flt$Sub_metering_2, type = "l", xlab = ' ', col = "red")
points(power_flt$timestp,power_flt$Sub_metering_3, type = "l", xlab = ' ', col = "blue")
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty = 1,  col= c("black", "red", "blue"))
dev.off()